import { useCallback, useState } from 'react';
import * as Crypto from 'expo-crypto';
import type { ConsentBlock } from '@frontdoorsales/flow-schema';

/**
 * D-17 lead-capture outcome: a rep may end a consultation as a lead
 * ("interested, no signature") ONLY after the customer confirms the curated
 * consent block (05-13 flow-schema addition). No confirmed consent → no lead
 * (abandonment ≠ consent). The lead row is written offline via the same
 * device-local plain-INSERT path as the other repos (flowDraftsRepo /
 * scanTelemetryRepo — Iron Rule 1, local-only); connector.ts's
 * applyLeadOperation drains it to the company-scoped `leads` table (0033) via a
 * plain INSERT (never ON CONFLICT), and the leads_insert_by_rep WITH CHECK
 * enforces consent_given=true server-side (T-05-43) as the belt to this
 * client-side suspenders.
 *
 * Pure DI'd function (`endConsultationAsLead`) + a thin useState hook wrapper
 * (`useEndAsLead`), mirroring useFlowDraft.ts's split so the gating logic is
 * unit-testable without a native SQLite/React runtime.
 */

/** Minimal PowerSync surface the lead write consumes (injectable for tests). */
export interface EndAsLeadDb {
  execute(sql: string, params?: unknown[]): Promise<unknown>;
}

/** The consent confirmation state read from the flow-runner's answers. */
export interface ConsentConfirmation {
  /** True only once the customer has affirmatively confirmed the consent block. */
  confirmed: boolean;
}

export interface EndAsLeadContact {
  name?: string | null;
  phone?: string | null;
  email?: string | null;
}

export interface EndAsLeadInput {
  companyId: string;
  repId: string;
  teamId: string;
  /** Attribution hint (D-17); may be device-local/unsynced, so nullable. */
  territoryId?: string | null;
  consent: ConsentConfirmation;
  contact: EndAsLeadContact;
  /** Free-text/product-slug the customer is interested in (leads.product_interest). */
  productInterest?: string | null;
  /** The pinned discount/terms version at capture time (leads.terms_version). */
  termsVersion?: number | null;
  /**
   * 0084 (§5.2) — the written offer left with the customer. Generated by the
   * CALLER (`generateOfferCode`) rather than here, so the sheet can show the
   * rep the exact code it is about to persist, and so this function stays a
   * pure write. All three travel together: no code, no offer.
   */
  offerCode?: string | null;
  offerExpiresAtIso?: string | null;
  /** Frozen copy of the terms discussed, so the offer PDF shows the real numbers. */
  offerSnapshot?: Record<string, unknown> | null;
}

function orNull<T>(value: T | undefined | null): T | null {
  return value === undefined || value === null ? null : value;
}

/**
 * Writes exactly one consent-gated lead row and returns its id. Throws (writing
 * nothing) when the consent block was not confirmed — D-17's hard client-side
 * gate. `consent_given` is written as `1` (true) unconditionally BECAUSE this
 * code path is only ever reached after a confirmed consent, so the persisted
 * lead can never carry a false consent flag.
 */
export async function endConsultationAsLead(
  db: EndAsLeadDb,
  input: EndAsLeadInput,
): Promise<string> {
  if (!input.consent.confirmed) {
    throw new Error(
      'cannot end consultation as a lead without a confirmed consent block (D-17: no consent, no lead)',
    );
  }

  const id = Crypto.randomUUID();
  const now = new Date().toISOString();

  // Plain local INSERT, never an upsert/ON CONFLICT (02-08 42501 trap +
  // ARCHITECTURE.md Iron Rule 3 standing ban) — mirrors scanTelemetryRepo.
  await db.execute(
    `INSERT INTO leads (
      id, company_id, rep_id, team_id, contact_name, contact_phone,
      contact_email, product_interest, consent_given, terms_version,
      territory_id, created_at, offer_code, offer_expires_at, offer_snapshot
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      id,
      input.companyId,
      input.repId,
      input.teamId,
      orNull(input.contact.name),
      orNull(input.contact.phone),
      orNull(input.contact.email),
      orNull(input.productInterest),
      1, // consent_given — always true here (guarded above), never persisted false
      orNull(input.termsVersion),
      orNull(input.territoryId),
      now,
      orNull(input.offerCode),
      orNull(input.offerExpiresAtIso),
      input.offerSnapshot ? JSON.stringify(input.offerSnapshot) : null,
    ],
  );

  return id;
}

export type EndAsLeadStatus = 'idle' | 'saving' | 'done' | 'error';

export interface UseEndAsLeadResult {
  endAsLead: (input: EndAsLeadInput) => Promise<string | null>;
  status: EndAsLeadStatus;
}

/**
 * Thin state-machine wrapper around `endConsultationAsLead` for the
 * EndAsLeadSheet outcome UI. A rejected consent gate surfaces as `error`
 * (the sheet keeps the consent block on screen); a successful write resolves
 * with the new lead id and moves to `done`.
 */
export function useEndAsLead(db: EndAsLeadDb): UseEndAsLeadResult {
  const [status, setStatus] = useState<EndAsLeadStatus>('idle');

  const endAsLead = useCallback(
    async (input: EndAsLeadInput): Promise<string | null> => {
      setStatus('saving');
      try {
        const id = await endConsultationAsLead(db, input);
        setStatus('done');
        return id;
      } catch {
        setStatus('error');
        return null;
      }
    },
    [db],
  );

  return { endAsLead, status };
}

/**
 * Derives the consent confirmation state for a given consent block from the
 * flow-runner's answers map (the block's answer holds `true` once confirmed,
 * exactly like the belehrung confirm signal). Centralized so both the sheet and
 * the outcome share one definition of "consent confirmed".
 */
export function isConsentConfirmed(
  block: Pick<ConsentBlock, 'id'>,
  answers: Record<string, unknown>,
): boolean {
  return answers[block.id] === true;
}
